/***************************************************************************
 *   Copyright 2008 James Hogan <james@albanarts.com>                      *
 *                                                                         *
 *   This file is part of KWorship.                                        *
 *                                                                         *
 *   KWorship is free software: you can redistribute it and/or modify      *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation, either version 3 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   KWorship is distributed in the hope that it will be useful,           *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with KWorship.  If not, see <http://www.gnu.org/licenses/>.     *
 ***************************************************************************/

#ifndef _KwAbstractLayer_h_
#define _KwAbstractLayer_h_

/**
 * @file KwAbstractLayer.h
 * @brief Layer interface class.
 * @author James Hogan <james@albanarts.com>
 */

#include <QSize>

class QWidget;

/// Abstract layer as part of display.
class KwAbstractLayer
{
  public:

    /*
     * Constructors + destructors
     */

    /// Default constructor.
    KwAbstractLayer();

    /// Destructor.
    virtual ~KwAbstractLayer();

    /*
     * Methods
     */

    /// Add widgets for this layer.
    virtual void* addWidgets(QWidget* master) const = 0;

    /// Remove the widgets generated by addWidgets.
    virtual void removeWidgets(QWidget* master, void* data) const = 0;
};

#endif // _KwAbstractLayer_h_

